services:
  - type: web
    name: gang-boyz-ecommerce
    env: node
    buildCommand: pnpm install --no-frozen-lockfile && pnpm run build
    startCommand: pnpm run start
    envVars:
      - key: NODE_ENV
        value: production