services:
  - type: web
    name: gang-boyz-ecommerce
    env: node
    buildCommand: pnpm install --no-frozen-lockfile && pnpm build
    startCommand: pnpm start
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 18